name: Blue/Green Deployment and Rollback

on:
  push:
    branches: [blue]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clona todo el historial

      - name: Configurar identidad de Git
        run: |
          git config --global user.name "alejandrolargo1031"
          git config --global user.email "alejandropulidolargo@gmail.com"

      - name: Simulación de pruebas automatizadas
        run: |
          echo "Ejecutando pruebas en la versión Blue..."
          sleep 3  # Simula el tiempo de ejecución de pruebas

          # Verifica si index.html contiene la versión esperada
          if grep -q 'data-version="Blue"' index.html; then
            echo "Pruebas exitosas"
          else
            echo "Pruebas fallidas"
            exit 1
          fi

      - name: Promover Blue a Green (Si las pruebas son exitosas)
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          git checkout green
          git merge origin/blue -m "Promoviendo la versión Blue a Green"

          # Modificar `index.html` para reflejar la nueva versión
          sed -i 's/data-version="Blue"/data-version="Green"/g' index.html
          git add index.html

          # Verifica si hay cambios antes de hacer commit
          if git diff --cached --quiet; then
            echo "No hay cambios en versión. Saltando commit..."
          else
            git commit -m "Actualizando versión a Green"
            git push origin green
          fi

      - name: Rollback si las pruebas fallan
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fallo detectado. Restaurando la última versión estable de Green..."
          git fetch origin green
          git checkout green
          git reset --hard origin/green

          # Restaurar `index.html` a Blue
          sed -i 's/data-version="Green"/data-version="Blue"/g' index.html
          git add index.html

          # Verifica si hay cambios antes de hacer commit
          if git diff --cached --quiet; then
            echo "No hay cambios en versión. Saltando commit..."
          else
            git commit -m "Restaurando versión a Blue"
            git push --force origin green
          fi
