name: Blue/Green Deployment and Rollback

on:
  push:
    branches: [blue]
  workflow_dispatch:

jobs:
  deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clona todo el historial

      - name: Configurar identidad de Git
        run: |
          git config --global user.name "alejandrolargo1031"
          git config --global user.email "alejandropulidolargo@gmail.com"

      - name: Simulación de pruebas automatizadas
        run: |
          echo "Ejecutando pruebas en la versión Blue..."
          sleep 3  # Simula el tiempo de ejecución de pruebas
          if grep -q "Estás viendo la versión <strong>Blue</strong>" index.html; then
            echo "Pruebas exitosas"
          else
            echo "Pruebas fallidas"
            exit 1
          fi

      - name: Promover Blue a Green (Si las pruebas son exitosas)
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git fetch origin
          git checkout green
          git merge origin/blue -m "Promoviendo la versión Blue a Green"
          
          echo "Green" > version.txt  # Actualizar archivo de versión
          git add version.txt
          git commit -m "Actualizando versión a Green"

          git push origin green

      - name: Rollback si las pruebas fallan
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Fallo detectado. Restaurando la última versión estable de Green..."
          git fetch origin green
          git checkout green
          git reset --hard origin/green
          
          echo "Blue" > version.txt  # Restaurar archivo de versión
          git add version.txt
          git commit -m "Restaurando versión a Blue"

          git push --force origin green
